language: node_js
node_js:
- stable
- '6'
- '4'
deploy:
  provider: heroku
  api_key:
    secure: osqzyfTIWmlpANLwNxMx09xuC4Vo+hSTZ/PgFc1JLijwf9+VpcdIKfyI//KyduK1Eckr1bdmv4brPoiYGUmaT3z61UTAfNPScHNBFU1ybOCq427vU2N/B0HNYZZvUoa0ScysVFaDmhfMZJ6FKqt/ZI9I/i/zCULd6iPPAXY9F+xIZ3klBCCTvpaSG6WAEZze+HBaup5oT0HVYEUTMTSaBy6PlOOG4FNTFgIZxCVR39UuUAGRDwNY+fbme+oddYM6BR8y8VAKYWbnjY2Ef4EHtuxIpG7Zsic2cCfgH0DTFQbFx4OXTcV4xooULSZCypAh3n4PViQ5hmac+pOB120NUxCW7wSnscgIO4qcH+voQrcU+SMCiMoLUDv80cpLeZ9554Y+6gaLr6kwId/YiIxbmLj2KfqWlI/bHfbyRDcBXlXRSUIGZe0eyT7YCrxnEzjDiDfI2bFN1AtUuiMdKPJMlqXc+e1QpmODu/WGmb/duA0OmoRiygJhgCmLHcKbmUSFXfULFmbyvh/5DJ/z3gpaQZFEk6FIx+3uUtRHCnntPYSwQPGHeiJLcWhPJruXN9ARGwpV4ky62NdbW0RyV/X/IgojJAhNisaoPoBtic7OfXqAa2NfS56JDerBwxvmGKmiskakjAy71AhluVK0T3NVJ5FGvemMj+TAxf7kzxE/lQ8=
  app: immense-sea-31485
  on:
    repo: adrianpearman/Travis_CLI_Example
env:
  global:
    secure: LS6sK1+LYvqcZuGxAEOwSR06YyM7VM9EoVKlN7+fTGOS4e0/pFQqw5DnSwjgqPLlrUqjl1nzAsrrXNneEUzSY/1DQYiNdOZShX4NpFEtwh8FMX+8HtFEm8Sr38Cw+MZ4E9iqY+1Lwc7kRYacUzb/Cza7h8Dw0ewlHo6R2a6y+O+LKHt8JK1jcISidZe8BMhqi/pV/xqJ91RUNmHt0d2czlWjy/6+cIgf+4VCa7pnwFtfyXTG/fWW9E2hVkkJBn9o2rgclhwOhxpgKwID1rjk0KrXxIbZyiF/DP1JNYIptbW7Ti35TYB6XjWx1VvPlHu9oMxmvcbCXFoPwBQtQMRP9umEVDSIPZeRLPOXc82hEbc7gwpx3fmcRTa+kWEAkRdutxa9QD9aO8qjTAsOBVOGZU5W51jkSOYAd73tw/FpQP6ksXQweBMT/SC0oewDwkpt/+P/PDyX5QwUOsz7kKTyqKsW87uaq674tOTgcvGQ5uEC9i0w8gIJCIm0kwruEOtRg86IIc21xDBj/5Q5UT80YaNXy/RZUE8hXZtKyL5HUt/yiidF5DrZFYL9e3nMLYMNAkgAZygOsMbs1JYu528B00NsydhjviQCcD5lQc+/3p5f2tXyuniiRXMfS046y5skoUbt5WVkTbeZ9PrcK6zc8pgO2nZTDfn7F19Q2xufLyo=
